// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMPfLnMA_cz6XiIQBV5Zfe5wsNW77Y4qc',
    appId: '1:818401911800:android:1c0a35ecea85927cb7ec0d',
    messagingSenderId: '818401911800',
    projectId: 'animista-app',
    storageBucket: 'animista-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefMLMmnNjWF7I4arv9TyNVaErdw_HxWQ',
    appId: '1:818401911800:ios:00ab38a36faae97cb7ec0d',
    messagingSenderId: '818401911800',
    projectId: 'animista-app',
    storageBucket: 'animista-app.appspot.com',
    androidClientId: '818401911800-5973ssfuke47jfcpk7vepsv2rck8oo29.apps.googleusercontent.com',
    iosClientId: '818401911800-1g7gq1v5agjjg685igjd9unpv7d14n1j.apps.googleusercontent.com',
    iosBundleId: 'fr.eilco.animista',
  );
}
